### ISSUE TITLE
It is not installed on Android 7.0

### ISSUE THREAD

**Issue by gowwe** [xeffyr/alpine-term#11]
It is not installed on Android 7.0 😢 Please solve the problem

**Comment by xeffyr** [comment]
1. How you are trying to install it ?
2. Are you updating or installing from scratch ?
3. Which version you are trying to install, "standard" or "ultimate"
variant ?
4. Where you have error, during installing apk or initialization ?

I should note that downgrading is not possible. Thus you can't install
v11.0 over v11.1. Installing "standard" version over "ultimate" also counts
as downgrade.

ср, 8 июл. 2020 г. в 18:11, Dragon 1X <notifications@github.com>:

**Comment by gowwe** [comment]
installing from scratch v10.0 Please solve
![Screenshot_20200709-063451](https://user-images.githubusercontent.com/54002951/86998580-fa8a6480-c1b0-11ea-87ff-4ae21f23d8a0.png)

**Comment by xeffyr** [comment]
> installing from scratch v10.0

Haven't you noticed that all versions LOWER than 11.0 were deleted from https://github.com/xeffyr/alpine-term/releases ?
Changelog also states: *All previous versions are now deprecated*.

You haven't answered my questions, so I literally doesn't know what exactly you are trying to do.

**Comment by xeffyr** [comment]
I do not have any problems with installation. All APKs were tested.

From screenshot at https://github.com/xeffyr/alpine-term/issues/11#issuecomment-655899120, I have noticed that you have low disk space:
![86998580-fa8a6480-c1b0-11ea-87ff-4ae21f23d8a0](https://user-images.githubusercontent.com/25881154/87096783-3f170e00-c24c-11ea-8fc6-95e75922a0eb.png)

You need 1 GB or **more** to be able to install my APKs. I'm not willing to make them smaller and in future I will leave only "max" build which requires 4GB space as minimum.

Alpine Term is not for devices with low disk space.
