### ISSUE TITLE
Switching between apps closes alpine-term

### ISSUE THREAD

**Issue by karthikeayan** [xeffyr/alpine-term#12]
**Type:**
- [x] Application bug
- [ ] OS bug

**Problem description**
When the alpine-term is running, switching to different app closes alpine-term. When switching back to alpine-term VM launches from the beginning.

**Steps to reproduce**
Open alpine-term
Press "App Overview" button
Select any other app
Press "App Overview" button
Select alpine-term

**Expected behavior**
VM should not launch from the beginning. It should be running.

**Comment by xeffyr** [comment]
1. How much RAM your device has?
2. What is a model or manufacturer of your device?

It seems your device uses some kind of aggressive RAM optimization and just kills the application when it goes to background. Alpine Term allocates 30 - 50% of the available RAM.

It may worth to check if your device requires granting of special permission for background process in Android settings.
