### ISSUE TITLE
Please add SSH support

### ISSUE THREAD

**Issue by JanuszChmiel** [xeffyr/alpine-term#13]
Dear Zephir,
I would like to valuably plea you, if yours .iso which boot by using Qemu could contain preconfigured SSH? So it would be automatically started at boot time? Or if no started automatically, it would run by typing ssh-run or similar word?
Termux contain ammazingly preconfigured dropbear. User simply install it and user type dropbear
and it is all.
I do not see at all. My goal is to try configuring yours Alpine so it will stream sound to Pulseaudio sound server which will run as A original Termux Android app.
Sure. May be, that you could consider try to add pulseaudio and sox to yours .apk if it is not too complex. But I know, that you do not want to include something which other users would not need.
I will try The speed. It will be very interesting to finally try to run some original Linux kernel on Android device.

**Comment by xeffyr** [comment]
> if yours .iso which boot

By default a pre-installed variant is booting.

> using Qemu could contain preconfigured SSH?

It already has SSH. You just need to start it and forward ports.

I will not make ports forwarded by default for these 2 reasons:
* Application intended to be isolated environment.
* There no guarantee that hardcoded port will not be already acquired by other application.

> So it would be automatically started at boot time?

Yes, it can be started automatically at boot time. However, I won't provide information about configuring the init system. Check Alpine Linux wiki for information on this. Or at least check the OpenRC documentation.

> Termux contain ammazingly preconfigured dropbear. User simply install it and user type dropbear
and it is all.

Let's clear things up: this is not Termux, but its opposite.

Termux is a terminal emulator for Android OS. Its designed to interact with its components. You can freely utilize Android OS resources where this is not restricted by permissions or SELinux.

Alpine Term is an isolated environment, with own, emulated hardware, Linux kernel and userland. It uses https://alpinelinux.org/ as operating system.

> My goal is to try configuring yours Alpine so it will stream sound to Pulseaudio sound server which will run as A original Termux Android app.

You won't be able to achieve that. Alpine Term does not emulate audio hardware nor will do that in future.

> May be, that you could consider try to add pulseaudio and sox to yours .apk if it is not too complex.

No, it won't be added. It is useless for the reason above and also will take space. I also tend to keep application minimal, with pre-installed packages which I use only.
