### ISSUE TITLE
How many data can i store to The running system?

### ISSUE THREAD

**Issue by JanuszChmiel** [xeffyr/alpine-term#14]
First of all I would like to congratulate you. You have invented unique approach, which allow visually impaired users with screen readers to use yours projectt. Because you have incorporated Termux accessibility support and you have setup Qemu so it send textual data output to Termux  process. So you have invented really new approach for Android. So I will be able to use yours system perfectly.
Which is maximum syze of installed data? Less than 1 GB or The syze is only limited by The free space inside Android device chips?
If syze is very limited for now, could be extended please?
Or all data are only stored in RAM so when I will shut down The image, installed data and changes are unfortunately lost?
Really, thank you for yours newest stable .apk package. Termux communicates with Qemu and all textual messages even kernel boot messages are accessible by visually impaired screen readers users.
I even think, that there will be many .apk modiffications based on yours work which will boot Debian, Ubuntu, Fedora and other X86 X64 images. I have a big plan with yours project and sure, I will ask you for The permission firstly before I would share my modiffication to  others and I will show you my work firstly.

**Comment by xeffyr** [comment]
> Which is maximum syze of installed data?

By default, partition has limit of 4 GB. I have made that to prevent application from eating all the available space of host device.

> If syze is very limited for now, could be extended please?

You can extend it on your own by using `fdisk` and `resize2fs`. There plenty of information on the Internet how to extend the disk partition.

> that there will be many .apk modiffications based on yours work which will boot Debian, Ubuntu, Fedora

I'm already providing images for Debian 10 and Arch Linux.

Ubuntu will not be ported. I have tried it, but its `snap` tool makes environment too slow. Even launching bash login shell takes 20 seconds or more.

> I will ask you for The permission firstly before I would share my modiffication to others

You can modify the APK in way you want. However if you decide to publish it somewhere, do not claim it as "original".

**Comment by JanuszChmiel** [comment]
And where are those next provided images?
Debian 10 and Arch Linux
Are also on Github? Please pot Me The link.
Really you have made Me A big joy. That I can read even kernel boot messages
thanks to build in Termux accessibility.
Di you tried build in sound support in Qemu, or does it really produce still
unusable results? So The best way is to combine standard Termux with
Pulseaudio with other process?

**Comment by xeffyr** [comment]
* Arch: https://github.com/xeffyr/alpine-term/releases/download/v11.1/archlinux-alpine-term-r2020.07.02.qcow2
* Debian: https://github.com/xeffyr/alpine-term/releases/download/v11.1/debian10-alpine-term-r2020.07.01-1.qcow2

Download one of them and save exactly as
```
/storage/emulated/0/Android/data/alpine.term/files/hdd.qcow2
```

**Comment by xeffyr** [comment]
> Di you tried build in sound support in Qemu, or does it really produce still
unusable results?

I have tried with outputting sound to file, but current QEMU version crashes when doing so.

Directly playing sound will require QEMU to be built with PulseAudio support. I will not do that as I don't want to have additional services running.

**Comment by JanuszChmiel** [comment]
aOh thank you very much for yours explanation. When I run some Linux distro
by using Proot, it is possible to stream sound by using TCP or Unix socket,
Pulseaudio on Termux must be running. So I would had to have normal Termux
which would run Pulseaudio. But may be, that hardware emulation could cause
so slowdowns that sound playback would be unusable too.
Thank you very much vor yours time and for yours explanation.
ESC key to recall BIOS must be very probably pressed very shortly after Qemu
loads. Because Before I press ESC key on A virtual Termux keyboard, Qemu
load Alpine.
