### ISSUE TITLE
port forwarding not working?

### ISSUE THREAD

**Issue by r3muxd** [xeffyr/alpine-term#15]
**Type:**
- [ ] Application bug
- [x] OS bug

**Problem description**

I don't know if there's a way to set up hostfwd for port forwarding.
**Steps to reproduce**

1. Start any program that binds to a local port
2. Try to access it anywhere else
**Expected behavior**

Program can access port

**Comment by xeffyr** [comment]
It works and in fact that's one of the features which I use too often.

https://xeffyr.github.io/alpine-term/docs/help.html#qemu-monitor

QEMU Monitor command: `hostfwd_add tcp::10022-:22`, where `10022` external port and `22` is internal port.
