### ISSUE TITLE
Unable to use root user

### ISSUE THREAD

**Issue by alexandrebfaust** [xeffyr/alpine-term#17]
**Type:**
- [ ] Application bug
- [ X ] OS bug

**Problem description**
I'm trying to use commands as root user but always returning a default message
"Sorry, user alpine is not allowed to execute '/bin/su' as root on alpine-term."
https://imgur.com/a/6TCVVLP

**Steps to reproduce**
I only installed the release version v11.1 ultimate
https://github.com/xeffyr/alpine-term/releases/download/v11.1/alpine-term-v11.1-ultimate.apk

**Expected behavior**
Run the command sudo su

**Comment by alexandrebfaust** [comment]
Oh f**k, just execute command with "sudo" and all is running perfectly

**Comment by alexandrebfaust** [comment]
Other case is running command "sudo rc-update add docker boot", return the same error "Sorry, user alpine is not allowed to execute '/sbin/rc-update add docker boot' as root on alpine-temp."

**Comment by xeffyr** [comment]
This is not a bug at all.

`sudo` configuration is not default. See `sudo -l` for allowed commands. To use `sudo rc-update add docker boot` you need to either to edit `sudoers` file or execute command in this way:
```
sudo -s
rc-update add docker boot
```

**Comment by xeffyr** [comment]
![Screenshot_20200728-234810_Alpine_Term](https://user-images.githubusercontent.com/25881154/88720116-040e4900-d12d-11ea-8bf7-b41227405039.png)

**Comment by xeffyr** [comment]
![Screenshot_20200728-235125_Alpine_Term](https://user-images.githubusercontent.com/25881154/88720317-57809700-d12d-11ea-8a1c-e8b52d6818b5.png)
