### ISSUE TITLE
is this subject to android 10 min sdk issue? 

### ISSUE THREAD

**Issue by hltdev8642** [xeffyr/alpine-term#21]
Hello,

I was just wondering if this app is going to have the same issues as termux is facing in Android 10?

If it isn't, just out of curiosity is this method only being ruled out because it would be too slow (I think I read on the termux issue page that this was the reason the qemu approach had been ruled out). 

I apologize if you are getting a million questions about this, I am just curious more then anything *I'm not intending to complain or be asking  "will my termux break or not" :)*

Thank you for all your great work, I have used your apps for years they are always first installs when I get a new device!

**Comment by xeffyr** [comment]
No, it is not affected by Android 10 restrictions.

Alpine Term is designed to run on Android 10+ and already uses SDK 29 - https://github.com/xeffyr/alpine-term/blob/master/alpine-term-app/app/build.gradle#L16.

Termux will not use QEMU to run environment. Info https://github.com/termux/termux-packages/wiki/Termux-and-Android-10#how-this-issue-is-going-to-be-solved.
