### ISSUE TITLE
Custom Command Line Arguments?

### ISSUE THREAD

**Issue by WMCB-Tech** [xeffyr/alpine-term#22]
Hey. is there a way to edit command line arguments in alpine term. so I can adjust the CPU cores and ram size. or enabling snapshot mode 

so is there a way like config file or .rc file?

**Comment by xeffyr** [comment]
Any config menu/options are out of scope - https://github.com/xeffyr/alpine-term/issues/18#issuecomment-666393659.

> so I can adjust the CPU cores and ram size

RAM size is managed automatically and specified value is reasonable to keep application stable and not being killed by Android.

> or enabling snapshot mode

Use `savevm` and `loadvm` for rolling back VM changes.

Snapshot mode was available previously as well as menu for enabling but both were removed.

> so is there a way like config file or .rc file?

Application does not provide access to its internals and also can't read the .rc files from QCOW disk image. Placing it on shared storage has impact on security.

**Comment by xeffyr** [comment]
If you need more customization, consider [Termux](https://termux.com) instead.

**Comment by WMCB-Tech** [comment]
Is the package `qemu-system-x86_64-headless` has Virtio features like. Virtio 9p., Virtio SCSI, Virtio RNG, Virtio Networking, or other Virtio drivers?

I'm sorry if I bother you a lot. because I was just curious on running Linux on Qemu in Android at reasonable speed

**Comment by xeffyr** [comment]
Yes, it has virtio.

**Comment by xeffyr** [comment]
Refer to https://github.com/xeffyr/alpine-term/blob/master/alpine-term-app/app/src/main/assets/vm_data/run-qemu.sh script, it uses nearly same config as Alpine Term. However you need to turn off KVM usage as `run-qemu.sh` is for use on PC.

**Comment by WMCB-Tech** [comment]
Hey. about that. can I use Alpine Term's Debian or Arch Alternate Images in Termux QEMU. so I don't need to install Debian from my PC. and transfer it to my phone.

**Comment by xeffyr** [comment]
@WMCB-Tech Yes you can. Just make sure you have created [necessary devices](https://github.com/xeffyr/alpine-term/blob/master/alpine-term-app/app/src/main/assets/vm_data/run-qemu.sh) on command line.
