### ISSUE TITLE
1 The application cannot be installed, version 11.0 and 11.1, APK signature 

### ISSUE THREAD

**Issue by gowwe** [xeffyr/alpine-term#24]
1 The application cannot be installed, version 11.0 and 11.1, APK signature problem, please solve the problem 2 Please support arm, arm64 and Saeon processor is the best Please respond

**Type:**
- [x] Application bug
- [ ] OS bug

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Comment by xeffyr** [comment]
Version 11.x is **deprecated**. Use v12.x instead.

Also: you can't install "standard" version over "ultimate" but only vice versa since technically "ultimate" build is update of "standard".

**Comment by gowwe** [comment]
Sorry For Disturb What is the problem? Watch the video
alpine-term-v11.1-ultimate.apk

في الأربعاء، ٩ سبتمبر، ٢٠٢٠ ٤:٢٧ م Leonid Pliushch <notifications@github.com>
كتب:

**Comment by xeffyr** [comment]
@gowwe You either read between lines or do not understand or just don't want to follow my recommendations. Uninstall the application than install again, if you have enough free space. If you don't have enough, then this is your problem.

Alpine Term is application for high-end devices with lots of free disk space.

**Comment by gowwe** [comment]
Thank you❤

في الخميس، ١٠ سبتمبر، ٢٠٢٠ ٩:٥٦ م Leonid Pliushch <notifications@github.com>
كتب:
