### ISSUE TITLE
Automatic RAM configuration differs on different occasions

### ISSUE THREAD

**Issue by xiongnemo** [xeffyr/alpine-term#25]
**Type:**
- [x] Application bug
- [ ] OS bug

**Problem description**

Experienced different automatic RAM configuration behavior when using different disk images to boot.

When using pre-configured Alpine Linux image, QEMU gives `1 GB` of RAM.

![Screenshot_2020-09-09-13-02-00-176_alpine term](https://user-images.githubusercontent.com/38759782/92558445-18ec0980-f2a1-11ea-9209-c0d1af1c635b.jpg)

When using pre-configured Debian Linux image given in [Release](https://github.com/xeffyr/alpine-term/releases/tag/v12.0), QEMU only gives `512 MB` of RAM.

![Screenshot_2020-09-09-13-01-53-306_alpine term](https://user-images.githubusercontent.com/38759782/92559127-8ea4a500-f2a2-11ea-8913-381d06d788b3.jpg)

Full process list is [here](https://github.com/xeffyr/alpine-term/files/5192811/process.list.txt):

```bash
sudo ps -aux > process.list.txt
```

Notice: The one with Debian Linux is of user_id 0, while the other is 999.

Phone mem stats:

![Screenshot_2020-09-09-13-02-08-404_com termux](https://user-images.githubusercontent.com/38759782/92558861-09b98b80-f2a2-11ea-9281-c05918011984.jpg)

Even if I did as what was said in `Adding more RAM` section in docs and reboot system, nothing works.

![Screenshot_2020-09-09-13-41-04-043_alpine term](https://user-images.githubusercontent.com/38759782/92558913-21910f80-f2a2-11ea-839f-b4c75d57b175.jpg)

**Steps to reproduce**

Install app, then boot from given Debian Linux image.

**Expected behavior**

Automatic RAM configuration should give 1 GB RAM.

**Comment by xeffyr** [comment]
On devices with large amount of RAM QEMU will provide 512M of pre-allocated RAM + 512M of default hot-pluggable RAM. Looks like Debian doesn't work well with RAM hot plugging.

You'll need to enable additional RAM through sysfs as in https://www.kernel.org/doc/html/latest/admin-guide/mm/memory-hotplug.html#logical-memory-hot-add-phase.

**This is not bug. Different operating systems (including kernel ver differences) have different behavior.**

**Comment by xiongnemo** [comment]
thx for your patience :)
