### ISSUE TITLE
New option for closing.

### ISSUE THREAD

**Issue by lars18th** [xeffyr/alpine-term#3]
Hi @xeffyr ,

First: Thank you for opening this issue section in this project (https://github.com/xeffyr/alpine-term/pull/2#issuecomment-623187779). :+1:

I want to comment here my suggestions for this interesting project. I'm sure you will don't want to implement all. But perhaps you accept to analyze some of the requests to make new improvements. I hope you will happy with constructive idea.

So, here my first suggestion: Please, can you provide a _simple_ and _intuitive_ option to close the Alpine-term process? At time, the `shutdown -h now` command doesn't work inside the terminal. Futhermore, no button or option is visible to terminate the process. So a "shutdown" button will be interesting.

What you think?

**Comment by xeffyr** [comment]
> Please, can you provide a simple and intuitive option to close the Alpine-term process?

QEMU Monitor --> enter command `quit`.
App is interface to QEMU and those who familiar with it know that command. If not, check QEMU monitor documentation.

`quit` command is dangerous from that side that it can cause file system corruption (just like power loss for hardware machine), so it is "hidden". Exit button was removed from notification in https://github.com/xeffyr/alpine-term/releases/tag/v10.0 and will not be added back.

**Comment by lars18th** [comment]
Hi @xeffyr ,

Thank you for the tip, and for the update of the README. :+1: 

However, one small suggestion: Add to the login description (inside the Alpine Linux) a line like this:
```
To close the emulator execute the command "poweroff" in the terminal console.
```

This is not intuitive and is not documented anywhere (I typically use `shutdown -h now` and not `poweroff`). And this has a lot of relevance because the potential disk corruption. For example, a power-off of the smartphone with the emulator running, can cause troubles. So the user requires to shutdown the emulator manually.

I hope you want to consider to add this simple warning.
Regards.

**Comment by xeffyr** [comment]
> This is not intuitive and is not documented anywhere

Documented as well as many other things.

**Comment by xeffyr** [comment]
![Screenshot_20200505-114813_Alpine Term](https://user-images.githubusercontent.com/25881154/81049171-5f31f600-8ec6-11ea-89f4-b755f0c78d04.jpg)

**Comment by lars18th** [comment]
> > This is not intuitive and is not documented anywhere
> 
> Documented as well as many other things.

Hi @xeffyr ,

I don't want to be dummy, but where is this message? I can't found it.

I discovery a few minutes ago that moving the finger from the left corner appears a window listing the terminals: [1] QEMU, [2] /dev/ttyS0, etc.
But, this **hidden** window is not documented anywhere. I suggest to describe this with images in the README. I'm sure you know very well this tool, but the UI is not intuitive. So it's required a minimal documentation.

In any case, thank you for this interesting project!
Regards.

**Comment by xeffyr** [comment]
This "hidden" window can be opened from context menu which is standard on Android btw - long tap on active screen field...

If page if so difficult to access -- > https://xeffyr.github.io/alpine-term/docs/help.html

**Comment by lars18th** [comment]
Great @xeffyr ,

I see the problem: In the README page *is not identified the Documentation*, I suggest to do this _small_ change at top:

```
Android application running Alpine Linux in the emulated x86_64 VM. Full Documentation at https://xeffyr.github.io/alpine-term/…
```

A small change with large results. :wink:
