### ISSUE TITLE
AlpineTerm won't work

### ISSUE THREAD

**Issue by ZhymabekRoman** [xeffyr/alpine-term#32]
**Type:**
- [x] Application bug: misbehaving of terminal emulator frontend.
- [ ] OS bug: boot issues and system misconfiguration.

**Problem description:**
I installed AlpineTerm Standard and ran it. The process of unpacking resources started, and then it just closed. I tried to re-open it, but it was showing something and closing abruptly. I managed to take one screenshot of this message: 
![Screenshot_20201015_120449](https://user-images.githubusercontent.com/61125068/96086495-44879280-0ee4-11eb-8b02-407d4eb797fe.jpg)

**Steps to reproduce:**
1) Download and install AlpineTerm Standard
2) Open it
3) Wait for closing and re - open

**Comment by ZhymabekRoman** [comment]
Android system version : 10 
Device : Samsung A10 
Termux works fine
What other data do you need to provide so that you can understand what's going on ?

**Comment by xeffyr** [comment]
No need to provide anything, I have crash log.
```
10-15 22:14:10.428  6913  6913 E AndroidRuntime: FATAL EXCEPTION: main
10-15 22:14:10.428  6913  6913 E AndroidRuntime: Process: alpine.term, PID: 6913
10-15 22:14:10.428  6913  6913 E AndroidRuntime: java.lang.NullPointerException
10-15 22:14:10.428  6913  6913 E AndroidRuntime: 	at java.util.Objects.requireNonNull(Objects.java:220)
10-15 22:14:10.428  6913  6913 E AndroidRuntime: 	at alpine.term.TerminalService.createQemuSession(TerminalService.java:241)
10-15 22:14:10.428  6913  6913 E AndroidRuntime: 	at alpine.term.TerminalActivity.lambda$onServiceConnected$3$TerminalActivity(TerminalActivity.java:556)
10-15 22:14:10.428  6913  6913 E AndroidRuntime: 	at alpine.term.-$$Lambda$TerminalActivity$0t-MH4i18VlP8dNvFlkueZR4BB8.run(Unknown Source:2)
10-15 22:14:10.428  6913  6913 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
10-15 22:14:10.428  6913  6913 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-15 22:14:10.428  6913  6913 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
10-15 22:14:10.428  6913  6913 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
10-15 22:14:10.428  6913  6913 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-15 22:14:10.428  6913  6913 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-15 22:14:10.428  6913  6913 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

I have managed to reproduce crash with "standard" apk on Android 11 emulator. Seems like issue is with getting path to application private directory on shared storage:
```
String workingDirPath = Objects.requireNonNull(getApplicationContext().getExternalFilesDir(null)).getAbsolutePath();
```
But in my case I was able to start application successfully after crash.

***

P.S. Never had this problem before and I really have no idea why `getExternalFilesDir()` will suddenly return `null` instead of path to directory. This also unreproducible with Alpine Term "ultimate" build which is installed to /system partition on my device with Lineage OS 17.1.

**Comment by xeffyr** [comment]
Try v13.1, with clearing app data or uninstalling: https://github.com/xeffyr/alpine-term/releases/download/v13.1/alpine-term-v13.1-standard-release.apk

**Comment by ZhymabekRoman** [comment]
> Try v13.1, with clearing app data or uninstalling: https://github.com/xeffyr/alpine-term/releases/download/v13.1/alpine-term-v13.1-standard-release.apk
Unfortunately, the problem remained. 
![Screenshot_20201016_091606](https://user-images.githubusercontent.com/61125068/96209106-b4ebed80-0f90-11eb-8bfb-b8fc5c158281.jpg)

**Comment by ZhymabekRoman** [comment]
Can you compile the debug version of AlpineTerm ? I will already send you the logs. It will be faster and more reliable.

**Comment by WMCB-Tech** [comment]
What's your Device RAM?

**Comment by ZhymabekRoman** [comment]
> How much your Device's RAM?

2 GB + 6 GB Swap file in SD card

**Comment by WMCB-Tech** [comment]
What is your Device's Kernel? maybe some linux binaries may not work on older linux kernels but can be hacked with proot

**Comment by ZhymabekRoman** [comment]
> What is your Device's Kernel? 

Linux 4.4 
![Screenshot_20201016_092839](https://user-images.githubusercontent.com/61125068/96209772-385a0e80-0f92-11eb-8ec8-536cd5b9a848.jpg)

**Comment by ZhymabekRoman** [comment]
> Alpine Term uses QEMU 5.x maybe some linux binaries may not work on older linux kernels 
I doubt it, I have QEMU + Proot working fine

**Comment by ZhymabekRoman** [comment]
Some logs : 
![Screenshot_20201016_094854](https://user-images.githubusercontent.com/61125068/96211154-59702e80-0f95-11eb-8eee-7d730dc0433c.jpg)

![Screenshot_20201016_095008](https://user-images.githubusercontent.com/61125068/96211134-4fe6c680-0f95-11eb-9a62-30f2fa6bb608.jpg)

**Comment by WMCB-Tech** [comment]
Do you have root?

**Comment by ZhymabekRoman** [comment]
> Do you have root?

Yes

**Comment by xeffyr** [comment]
> Unfortunately, the problem remained.

@ZhymabekRoman Even with full re-installation?

> Can you compile the debug version of AlpineTerm ?

Yes, will do that.

> Some logs :

I don't see anything related to crash on these screenshots.

Need full trace beginning from `AndroidRuntime: FATAL EXCEPTION: main`.

***

> What is your Device's Kernel? since Alpine Term uses QEMU 5.x maybe some linux binaries may not work on older linux kernels

@WMCB-Tech QEMU was never dependent on Linux version.

**Comment by xeffyr** [comment]
Try https://github.com/xeffyr/alpine-term/releases/download/v13.1/alpine-term-v13.1-standard-debug.apk

**Comment by ZhymabekRoman** [comment]
> @ZhymabekRoman Even with full re-installation?

Yes

> Try to get logs from https://github.com/xeffyr/alpine-term/releases/download/v13.1/alpine-term-v13.1-standard-debug.apk

[logs-2020-10-16-23-39-07.zip](https://github.com/xeffyr/alpine-term/files/5393423/logs-2020-10-16-23-39-07.zip)
[logs-2020-10-16-23-38-34.zip](https://github.com/xeffyr/alpine-term/files/5393425/logs-2020-10-16-23-38-34.zip)

**Comment by xeffyr** [comment]
Next things I can do:
* Backport https://github.com/termux/termux-app/commit/5a70be152346958009fda0419d77502c6e52391b from Termux - to flush stdout when process exits.
* Disable auto-close for debug builds.

This will allow to get some information if there is problem with starting QEMU.

Also I can make a bundle of QEMU from Alpine Term for launching in Termux to see whether binary is actually working.

That's unlikely that Alpine Term hit [execve() problem](https://github.com/termux/termux-app/issues/1072) on Android 10 as binaries are placed to allowed location and I don't see any AVC denials in log regarding Alpine Term.

**Comment by xeffyr** [comment]
A bundle with original ARM `qemu` binary from Alpine Term, launch script and FreeDOS image for testing: [qemu-bundle-armeabi.tar.gz](https://github.com/xeffyr/alpine-term/files/5393951/qemu-bundle-armeabi.tar.gz)

How to use (in Termux):
```
curl -LO https://github.com/xeffyr/alpine-term/files/5393951/qemu-bundle-armeabi.tar.gz
tar zxf qemu-bundle-armeabi.tar.gz
cd qemu-bundle
./exec.sh
```

Normally you should see *FreeDOS* boot logs. If QEMU failed to start, post screenshot there.

**Comment by xeffyr** [comment]
New builds are available:
* https://github.com/xeffyr/alpine-term/releases/download/v13.2/alpine-term-v13.2-standard-debug.apk
* https://github.com/xeffyr/alpine-term/releases/download/v13.2/alpine-term-v13.2-standard-debug-nostorage.apk - special build without storage support, to exclude https://github.com/xeffyr/alpine-term/issues/32#issuecomment-709542051.

With these builds application should no longer close if session failed to start. In case of error, you should be able to see some info in monitor session - any permission denials, segmentation faults, unknown command line arguments, etc.

**Comment by ZhymabekRoman** [comment]
> A bundle with original ARM `qemu` binary from Alpine Term, launch script and FreeDOS image for testing: [qemu-bundle-armeabi.tar.gz](https://github.com/xeffyr/alpine-term/files/5393951/qemu-bundle-armeabi.tar.gz)
> Normally you should see _FreeDOS_ boot logs. If QEMU failed to start, post screenshot there.

FreeDOS excellent started and working: https://youtu.be/ROSb7pdaPBA


> New builds are available:
> 
> * https://github.com/xeffyr/alpine-term/releases/download/v13.2/alpine-term-v13.2-standard-debug.apk

![Screenshot_20201017-083823_Alpine Term](https://user-images.githubusercontent.com/61125068/96326754-37d67c00-1055-11eb-9e9c-93fa368688de.jpg)

**Comment by WMCB-Tech** [comment]
@ZhymabekRoman Have you tried the nostorage variant?

**Comment by xeffyr** [comment]
Ok, I have found where is error:
```
processArgs.addAll(Arrays.asList("-m", "512M,slots=4,maxmem=16384M"));
```
We can't have `maxmem` more than `4095M` on 32bit host.

Next release will fix this. Probably memory hot-plugging will also be changed to rely on `virtio-balloon` instead of messing around with RAM slots.

> Have you tried the nostorage variant?

No need to try it.

**Comment by xeffyr** [comment]
Fixed in https://github.com/xeffyr/alpine-term/commit/64938de6ef41a1ebd4e86cd8002fa8b7cc748557.

Now Alpine Term will use exactly 32% of host memory for virtual machine and 8% for TCG buffer. That will be more flexible than using hardcoded values or via hot-plugging and also safe from accidental killing of Alpine Term by Android OS in most cases.

**Comment by BardiaMGTGC** [comment]
so when will this build be out for downloads?
