### ISSUE TITLE
possible to use alpine-term with armhf?

### ISSUE THREAD

**Issue by BardiaMGTGC** [xeffyr/alpine-term#33]
i wanted to use this on armhf (it works perfectly on arm64 which i tested but gives an error and crashes on armhf)
i thought the crash might be because of the image but after a bit of thinking seems like its not
i tried another qemu android app but no success as of i couldnt get any of the 10 images i had to boot(kali live would boot which had gui and was a live image so useless to me) 
anyway i can get this working on armhf?

**Comment by WMCB-Tech** [comment]
Same issue with [#32](https://github.com/xeffyr/alpine-term/issues/32)

**Comment by BardiaMGTGC** [comment]
im actually running armv7 in the other issue he is running armv8
so while i was testing qemu today anything higher than 450mb of ram would crash the app(with a 2gb device)
maybe do a build with like 400 or 300mb of ram at default?

**Comment by xeffyr** [comment]
Answering:
> possible to use alpine-term with armhf?

Possible on any Android device with AArch64 (equivalent of ARM64), ARM (equivalent of ARMHF), i686 (x86 32bit), x86_64.

Tested on any of these architectures and it worked perfectly.

> so while i was testing qemu today anything higher than 450mb of ram would crash the app(with a 2gb device)

This is something unexpected. Android usually starts to kill processes using *more than 50% of available RAM*. In fact, it even may not kill processes using 60-70% of memory.

On my ARM (armhf) device with 1 GB of RAM it works without issues though. There is something wrong with *your device* or crash was not related to RAM issues.

Can you tell me how you changed the RAM size to determine the crash?

> maybe do a build with like 400 or 300mb of ram at default?

No need to do that. QEMU does not allocate all this memory at start immediately.

So if you want to have lower amount of RAM, do this:
1. At Alpine Term start, immediately switch to QEMU monitor console.
2. Type `balloon 256` - this will set amount of memory to 256M. You may set higher value.

Please note that Alpine Term has been tested on each of aarch64, arm, i686, x86_64 architecture with different RAM configurations 1 - 4 GB and confirmed to work properly. Support of low-end devices and also devices with aggressive power-saving or memory optimizing is out of scope.
