### ISSUE TITLE
Network of Arch Linux dosen't work

### ISSUE THREAD

**Issue by scratch-er** [xeffyr/alpine-term#34]
**Type:**
- [ ] Application bug: misbehaving of terminal emulator frontend.
- [X] OS bug: boot issues and system misconfiguration.

**Problem description:**

**Steps to reproduce:**

**Expected behavior:**

**Comment by WMCB-Tech** [comment]
Have you tried starting the dhcpcd service?

**Comment by scratch-er** [comment]
It turns out that the default DNS server in /etc/resolv.conf isn't accessible. I have replaced it with an accessible one and it works.
