### ISSUE TITLE
Configurable mounts

### ISSUE THREAD

**Issue by lars18th** [xeffyr/alpine-term#4]
Hi @xeffyr ,

My second suggestion is related to the mounts of the Alpine-term virtual machine. For a more flexible environment, I suggest for these two changes in the environment:

- The first one is to add support for multiple image files. My objective is to use two independent images: one for the system and one for the home (that's one for `/` and one for `/home`).
- The second suggestion is to leave the option for selecting the path of the image files. For example, I want to put the home image in the SD card, and the system (root) in the internal memory.

I'm not sure if these changes are difficult or simple to implement. But in any case, the objective is to provide a tool for changing the images. This will provide more flexibility to the user to manage/backup the environment.

What you think?

**Comment by xeffyr** [comment]
> The first one is to add support for multiple image files.

Put your drive image into
```
/sdcard/Android/data/alpine.term/files
```
then in QEMU monitor:
```
drive_add 0 if=none,file=./IMAGE_NAME,id=hd1
device_add scsi-hd,id=scsi-hd1,drive=hd1
```
Image file can be created either by external application (Termux) or directly from Alpine Term shell with `qemu-img`.

> that's one for / and one for /home

Such configuration is not supported. Primary drive is stored always in `/data/data/alpine.term/files` where it can't be accessed by other applications intentionally.

However you can add new image through QEMU monitor, it will be visible in VM as soon as you didn't exited the application.

> The second suggestion is to leave the option for selecting the path of the image files. 

Option for adding secondary image file was removed among with SD card permission as it won't be supported on Android 10 but I want to have same interface on all Android versions.

Path `/sdcard/Android/data/alpine.term/files` does not require any permissions as considered to be private directly same as `/data/data/alpine.term/files`.

I also want to keep app minimal, and features that can be used through QEMU monitor won't be exposed through app interface. See commands above for adding custom drive.

Backup can be done with QEMU monitor too, use command `drive_backup`:
```
drive_backup -f -c hd0 ./my_backup.qcow2
```
Restoring can be done with this commands (idea is to overwrite primary image):
```
stop
device_del scsi-hd0
drive_add 0 if=none,id=tmp-hd,format=qcow2,file=./my_backup.qcow2
device_add scsi-hd,id=scsi-hd0,drive=tmp-hd
drive_backup -f -c tmp-hd /data/data/alpine.term/files/run/alpine-linux-hdd.qcow2
```
Command `drive_backup` is not blocking ! Check its state with `info block-jobs` and wait until finishes. After finish execute command `quit` (there are ways to not use `quit` such as live snapshots, but they are tricky).

**Comment by lars18th** [comment]
Hi @xeffyr ,

Thank you. I'll do some tests with custom images. However, I don't know where is the "QEMU monitor" of Alpine-Termux. Please, can you explain how to access to it and execute these commands?

Thank you!

**Comment by xeffyr** [comment]
> However, I don't know where is the "QEMU monitor"

First session tab in drawer.
