### ISSUE TITLE
Pip install (module) freeze the terminal every time.

### ISSUE THREAD

**Issue by darklord-666** [xeffyr/alpine-term#6]
Everything is working fine except if i tried to install any pip modules using this command pip install (module_name) the terminal hang and it stuck even i reset the terminal... Everytime it freezes when i give pip command..

**Comment by xeffyr** [comment]
Installing python modules from source isn't good idea. Emulator performance is low, more than 100-150 times slower than host. Consider looking the package repository for python modules, usually prefixed with `py3-`.
