### ISSUE TITLE
How to access QEMU Monitor

### ISSUE THREAD

**Issue by lephamduythong** [xeffyr/alpine-term#9]
How can I press key on phone to access QEMU monitor to edit port forwarding to use ssh, can you explain the way ? I have tried "Ctrl + Alt + 2" on google but it doesn work. I dont want to use NAT mode network with QEMU, I d'like BRIDGE mode to easy connect to my local network as Termux does, do u have any idea about this ?

**Comment by xeffyr** [comment]
Look on session tabs no ?

**Comment by xeffyr** [comment]
> I dont want to use NAT mode network with QEMU, I d'like BRIDGE mode to easy connect to my local network as Termux does, do u have any idea about this ?

This isn't possible. TUN/TAP requires QEMU to be launched as root. Application will never use root and supports only user mode networking.

**Comment by lephamduythong** [comment]
> Look on session tabs no ?

I cant find that sessions tab, can you explain step by step ?
https://ibb.co/zVqVfTK

**Comment by xeffyr** [comment]
https://xeffyr.github.io/alpine-term/docs/help.html#navigation-drawer

**Comment by lephamduythong** [comment]
> https://xeffyr.github.io/alpine-term/docs/help.html#navigation-drawer

Ok i found it, thanks
